"""AI-assisted golden-set labeling.

Documented limitation (see DECISION_LOG.md): the golden set's true_intent /
true_escalation labels were generated by an LLM applying labeling_guide.md's
rubric, not independently hand-labeled by a human. This is disclosed
prominently in the eval report -- using an LLM to label ground truth that
then grades an LLM-based classifier/judge risks correlated errors, which is
exactly the kind of thing that should weaken (not inflate) confidence in the
headline numbers.

Any example already labeled by a human (via the labeling artifact) is left
untouched -- those take priority and are never overwritten by an AI label.
"""
from __future__ import annotations

import json
import logging
import os

import pandas as pd
import yaml

from pipeline.config import ARTIFACTS_DIR, TAXONOMY_YAML
from pipeline.llm_client import LLMClient

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

GOLDEN_SET_RAW_PARQUET = ARTIFACTS_DIR / "golden_set_raw.parquet"
GOLDEN_LABELS_JSON = ARTIFACTS_DIR / "golden_labels.json"

LABELING_MODEL = os.environ.get("GENERATION_MODEL", "gemini-3.5-flash")
LABELING_TEMPERATURE = 0.0


def _load_taxonomy_intents(path=TAXONOMY_YAML) -> list[dict]:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)["intents"]


def build_labeling_prompt(
    customer_msg: str,
    brand_reply: str,
    followup_msg: str | None,
    turn_count: int,
    intents: list[dict],
) -> str:
    intent_block = "\n".join(f"- {i['id']}: {i['description'].strip()}" for i in intents)
    valid_ids = [i["id"] for i in intents]
    followup_line = f'\nCustomer follow-up: "{followup_msg}"' if followup_msg else ""

    return f"""You are hand-labeling a support-ticket golden set for evaluation, acting
as a careful Tier-1 support agent making a judgment call. Follow this rubric
exactly.

Intents (pick exactly one):
{intent_block}

true_escalation rubric:
- escalate: the issue needs account-specific action the brand can't do in a
  public/templated reply, the customer is visibly upset after repeated
  contact, there's any safety/legal/financial-harm language, or the "right"
  reply isn't obvious from precedent.
- auto_handle: the issue is a known, templatable fix (password reset link,
  standard troubleshooting step, FAQ-style answer) and the customer's tone
  doesn't suggest they're already frustrated.

Customer message: "{customer_msg}"{followup_line}
(For reference only, not the answer to grade) How the brand actually replied: "{brand_reply}"
Turn count: {turn_count}

Respond with ONLY a JSON object:
{{"true_intent": "<one of {valid_ids}>", "true_escalation": "auto_handle"|"escalate", "ambiguous_note": "<empty string, or one sentence if genuinely unclear>"}}
No other text."""


def _parse_response(raw: str, valid_ids: list[str]) -> dict:
    text = raw.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("json"):
            text = text[4:]
    data = json.loads(text)
    if data["true_intent"] not in valid_ids:
        raise ValueError(f"invalid intent {data['true_intent']!r}")
    if data["true_escalation"] not in ("auto_handle", "escalate"):
        raise ValueError(f"invalid escalation {data['true_escalation']!r}")
    return {
        "true_intent": data["true_intent"],
        "true_escalation": data["true_escalation"],
        "ambiguous_note": data.get("ambiguous_note") or "",
        "label_source": "ai_generated",
    }


def label_example(row: pd.Series, client: LLMClient, intents: list[dict]) -> dict:
    prompt = build_labeling_prompt(
        row["customer_msg_clean"],
        row["brand_reply_clean"],
        row.get("followup_msg"),
        int(row["turn_count"]),
        intents,
    )
    valid_ids = [i["id"] for i in intents]
    raw = client.generate(LABELING_MODEL, prompt, params={"temperature": LABELING_TEMPERATURE})
    return _parse_response(raw, valid_ids)


def run(
    raw_path=GOLDEN_SET_RAW_PARQUET,
    existing_labels_path=GOLDEN_LABELS_JSON,
    out_path=GOLDEN_LABELS_JSON,
) -> dict:
    raw = pd.read_parquet(raw_path)
    intents = _load_taxonomy_intents()
    client = LLMClient()

    labels: dict[str, dict] = {}
    if existing_labels_path.exists():
        with open(existing_labels_path, "r", encoding="utf-8") as f:
            labels = json.load(f)

    human_labeled = {tid for tid, l in labels.items() if l.get("label_source") != "ai_generated"}
    logger.info("preserving %d existing (human) labels", len(human_labeled))

    to_label = raw[~raw["thread_id"].isin(labels.keys())]
    logger.info("labeling %d examples with %s", len(to_label), LABELING_MODEL)

    for i, (_, row) in enumerate(to_label.iterrows()):
        try:
            labels[row["thread_id"]] = label_example(row, client, intents)
        except Exception as e:
            logger.warning("failed to label %s: %s", row["thread_id"], e)
        if (i + 1) % 20 == 0:
            logger.info("labeled %d/%d", i + 1, len(to_label))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(labels, f, indent=2, ensure_ascii=False)

    logger.info("wrote %d total labels to %s", len(labels), out_path)
    return labels


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()
    run()
